theme: jekyll-theme-architect

plugins:
- jekyll-pwa-plugin

locale: ru_RU

# Progressive Web Apps
pwa:
  enabled: true # Optional
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 5 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "{js,css,fonts}/**/*.{js,css,eot,svg,ttf,woff}"
    - index.html
  precache_glob_ignores: # Optional
    - sw-register.js
    - "fonts/**/*"