theme: jekyll-theme-architect

locale: ru_RU


title: Блокировки в России
description: "Альманах пользователя интернета"
keyword: "блокировки сайтов в россии, блокировка в россии, 	блокировка рф, роскомнадзор, блокировка впн в россии"
SEOTitle: Блокировки в России
email: fuckfucksociety@protonmail.com